Upgrades from Ingress API from extensions/v1beta1 to networking.k8s.io/v1
Azure/application-gateway-kubernetes-ingress pull request #1197
Opened 2021-06-23 23:45 UTC by erickhernandezascencio

## Checklist
- [X ] The title of the PR is clear and informative
- [X ] If applicable, the changes made in the PR have proper test coverage
- [ ] Issues addressed by the PR are mentioned in the description followed by `Fixes`.

## Description

Updates k8s version from extensions/v1beta1 to networking.k8s.io/v1. Change is required as previous version will be deprecated in future k8s versions.

## Fixes

N/A

2021-07-01 00:32 UTC, akshaysngupta requested changes
left comments

2021-07-01 00:32 UTC, akshaysngupta commented on pkg/k8scontext/k8scontext_suite_test.go
> +	// "k8s.io/klog/v2"
remove comment

2021-07-01 00:32 UTC, akshaysngupta commented on pkg/tests/fixtures.go
> +	return &networking.Ingress{
was this failing to serialize ?

2021-07-01 00:32 UTC, akshaysngupta commented on pkg/appgw/frontend_listeners.go
> +func attachFirewallPolicy(cbCtx *ConfigBuilderContext, ingress *networking.Ingress, azConfig *listenerAzConfig) {
I think we removed this function.

2021-07-01 14:34 UTC, akshaysngupta commented
this pr will need follow up with tests

2021-07-01 16:13 UTC, erickhernandezascencio commented on pkg/tests/fixtures.go
> +	return &networking.Ingress{
yep, was returning nil

2021-07-01 20:20 UTC, erickhernandezascencio commented on docs/how-tos/lets-encrypt.md
> +                name: frontend
unsure what you mean. i think indentation is correct?

2021-07-06 16:23 UTC, akshaysngupta reviewed
Looking good so far!

2021-07-07 18:07 UTC, akshaysngupta commented on pkg/appgw/health_probes.go
> +	probe.Name = to.StringPtr(generateProbeName(backendID.Path.Backend.Service.Name, serviceBackendPortToStr(backendID.Path.Backend.Service.Port), backendID.Ingress))
need to make sure there is a test for service == nil

2021-07-07 18:17 UTC, akshaysngupta commented on pkg/tests/ingress-complex.yaml
> +            pathType: Prefix
will need to handle pathType

2021-07-07 18:23 UTC, akshaysngupta commented on pkg/k8scontext/context.go
> +func (c *Context) UpdateIngressStatus(ingressToUpdate networking.Ingress, newIP IPAddress) error {
TODO: check if ingress v1beta1 is updated correctly

2021-07-07 18:23 UTC, akshaysngupta approved these changes
I have added few comments that need to be addressed in subsequent PRs

2021-07-07 18:24 UTC, merged