Enable the CORS header for AGIC
Azure/application-gateway-kubernetes-ingress pull request #1315
Opened 2021-12-28 08:26 UTC by rachitkumar13

## Checklist
- [ ] The title of the PR is clear and informative
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] Issues addressed by the PR are mentioned in the description followed by `Fixes`.

## Description

## Fixes

2022-01-12 19:51 UTC, akshaysngupta commented
@rachitkumar13 is this PR ready for review ?

2022-01-17 08:22 UTC, rachitkumar13 commented
> @rachitkumar13 is this PR ready for review ?

Yes

2022-01-31 06:30 UTC, akshaysngupta commented on docs/annotations.md
> +    appgw.ingress.kubernetes.io/appgw-cors-enable: true/false
How about we shorten the key to "enable-cors"

2022-02-15 19:37 UTC, akshaysngupta commented on pkg/appgw/requestroutingrules_test.go
> +		for i := 0; i < len(*ruleSets); i++ {
This line is throwing nil exception in the test
![image](https://user-images.githubusercontent.com/5294363/154135961-7cf9909e-db90-46c2-9cb6-54dd530b6a41.png)

2022-02-15 19:37 UTC, akshaysngupta requested changes
Please address the comments

2022-07-29 18:35 UTC, closed without merging